import Button from "@/app/components/Button";
import Image from "next/image";
import thumb from "@/public/image/pic.jpg"
export const metadata = {
    title: "mission",
    description: "Generated by create next app",
  };
const page = () => {
    return (
        <div className="font-[poppines]">
            mission
            <div>
            <Image 
            src={thumb}
            alt="pic"
            height="300"
            width="800"
            quality={100}
            placeholder="blur"
            ></Image>
            </div>
            <div className='mt-5 ml-5'>
                <Button></Button>
            </div>
        </div>
    );
};

export default page;